
image kitchen L_pajama_s2_nor_H_whitesatin_s0_nor_1 = RENPY_IMG_PATH + f"Leyla_Expr1_Pose1__ClothPajama1__Hannah_Expr1_Pose1__ClothWhiteSatin2__Inter0__FullBody_Kitchen.png"
image kitchen L_pajama_s2_nor_H_whitesatin_s0_nor_2 = RENPY_IMG_PATH + f"Leyla_Expr1_Pose1__ClothPajama1__Hannah_Expr1_Pose1__ClothWhiteSatin2__Inter0__FullBody_Kitchen_1.png"
image kitchen L_pajama_s2_nor_H_whitesatin_s0_nor_3 = RENPY_IMG_PATH + f"Leyla_Expr0_Pose1__ClothPajama102__Hannah_Expr0_Pose1__ClothWhiteSatin1__Inter0__FullBody_Kitchen.png"
image kitchen L_pajama_s2_nor_H_whitesatin_s0_nor_4_touch = RENPY_IMG_PATH + f"Leyla_Expr0_Pose1__ClothPajama102__Hannah_Expr0_Pose1__ClothWhiteSatin1__Inter0__FullBody_Kitchen_3.png"
image kitchen L_pajama_s2_nor_H_whitesatin_s0_nor_5_touch = RENPY_IMG_PATH + f"Leyla_Expr0_Pose1__ClothPajama102__Hannah_Expr0_Pose1__ClothWhiteSatin1__Inter0__FromBehind_Kitchen_4.png"
image kitchen L_pajama_s2_nor_H_whitesatin_s0_nor_6_touch_POV = RENPY_IMG_PATH + f"Leyla_Expr0_Pose1__ClothPajama102__Hannah_Expr0_Pose1__ClothWhiteSatin1__Inter0__FromBehind_Kitchen_POV.png"
image kitchen L_pajama_s2_nor_H_whitesatin_s0_nor_7_touch_POV = RENPY_IMG_PATH + f"Leyla_Expr0_Pose1__ClothPajama102__Hannah_Expr0_Pose1__ClothWhiteSatin1__Inter0__FromBehind_Kitchen_POV2.png"
